[project]
name = "{{ cookiecutter.__package_name }}"
dynamic = ["version"]
description = "{{ cookiecutter.project_name }} package"
readme = "README.md"
requires-python = ">={{ cookiecutter.python_version }}"
license = "MIT"
authors = [
    { name = "{{ cookiecutter.client_name }}", email = "contact@{{ cookiecutter.client_name }}.com"}
]
keywords = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: {{ cookiecutter.python_version }}",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/{{ cookiecutter.client_name }}/{{ cookiecutter.repo_name }}"
"Bug Reports" = "https://github.com/{{ cookiecutter.client_name }}/{{ cookiecutter.repo_name }}/issues"
"Source" = "https://github.com/{{ cookiecutter.client_name }}/{{ cookiecutter.repo_name }}"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"