site_name: "ds-template"
site_description: "A comprehensive project template generator for data science and Python projects with AI-powered generation capabilities"
site_author: "deepsense.ai"
copyright: "2023, deepsense.ai"

repo_url: https://github.com/deepsense-ai/ds-template/
repo_name: ds-template

# Theme configuration - using Material theme for modern appearance
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
    - palette

# Navigation structure
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - AI-Powered Generation: ai_features.md
  - Template Content:
    - template_content.md
    - Python Structure: tmp_content/python_structure.md
    - Code Quality: tmp_content/precommit.md
    - Development Tools: tmp_content/mise.md
    - GitLab CI: tmp_content/gitlab_ci.md
    - GitHub CI: tmp_content/github_ci.md
    - Semantic Versioning: tmp_content/semver_package.md

# Plugins
plugins:
  - search
  - mermaid2

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      baselevel: 1
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

# Additional CSS
extra_css:
  - assets/extra.css

# Static files directory
docs_dir: docs
site_dir: site

# Build settings
strict: true