[project]
name = "ds-templater"
version = "0.1.0"
description = "Template management system for data science projects"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "pyyaml>=6.0.2,<7.0.0",
    "questionary>=2.1.0",
    "typer>=0.9.0",
    "rich>=13.9.4",
    "loguru>=0.7.3",
    "pydantic>=2.10.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/ds_templater"]