name: 🐞 Bug Report
description: File a bug report
title: "bug: <short_name>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: XYZ doesn't work as expected...
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id : how-to-reproduce
    attributes:
      label: How can we reproduce it?
      description: Please provide steps (commands) that led you to the bug.
      placeholder: cookiecutter git@github.com:deepsense-ai/ds-template.git
      render: bash
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell