name: Build documentation

on:
  push:
    branches: [main, master]

jobs:
  pages:
    runs-on: ubuntu-latest
    container: python:3.11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          apt-get update && apt-get install -y curl
          curl -fsSL https://astral.sh/uv/install.sh | sh
          echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install Dependencies
        run: uv pip sync

      - name: Build docs
        run: ./build_docs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
