name: Build documentation

on:
  push:
    branches: [main, master]

jobs:
  pages:
    runs-on: ubuntu-latest
    container: python:3.11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # for best results, it is better to generate
      # documentation within development environment
      - name: Setup venv
        run: . ./setup_dev_env.sh

      - name: Cache uv
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}

      - name: Build docs
        run: ./build_docs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
